---
 - name: Deploy to tomcat
   hosts: web
   become: yes
   tasks:
    - name: Copy WAR file
      copy:
        src: "/var/snap/jenkins/4874/workspace/MyWeb/target/MyWeb.war"
        dest: "/opt/tomcat/webapps/MyWeb.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
